---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v0-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v0-yarn-{{checksum ".circleci/config.yml"}}
      - run: yarn
      - run: yarn add -D nyc@13 @oclif/nyc-config@1
  node-12:
    <<: *test
    docker:
      - image: node:12
  node-10:
    <<: *test
    docker:
      - image: node:10

workflows:
  version: 2
  test:
    jobs:
      - node-latest
      - node-12
      - node-10
  dependabot-automerge:
    triggers:
      - schedule:
          cron: '0 2,5,8,11 * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/dependabot-automerge
